"""Export the Python engine's typography for the independent browser editor."""
import json
import sys
from dataclasses import asdict
from pathlib import Path

root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root / "artifacts/api-server/python"))
from docclass import CLASSES
from styles import BASE_SPEC

payload = {"default": asdict(BASE_SPEC), "classes": {
    key: asdict(value.typography) for key, value in CLASSES.items()
}}
target = root / "packages/editor-core/src/templates.generated.ts"
content = "// Generated by scripts/generate_editor_templates.py. Do not edit.\nexport const templateData = " + json.dumps(payload, indent=2) + ";\n"
if "--check" in sys.argv:
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        sys.exit("Editor templates are stale. Run npm run generate:editor-templates.")
    print("Editor templates match the export engine.")
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")
    print("Generated editor templates.")
